repos:

  - repo: local
    hooks:
      - id: just-fmt
        name: just --fmt
        entry: sh -c 'for file do just --fmt --justfile "$file" || exit; done' --
        language: system
        files: '(?i)(^|/)\.?justfile$|\.just$'
        types: [file]
