name: 'Forbid Merge Commits'
description: 'A composite action to forbid merge commits in pull requests.'
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Check for merge commits
      run: |
        set -Eeuo pipefail

        git fetch origin ${{github.base_ref}}:${{github.base_ref}} ${{github.head_ref}}:${{github.head_ref}}

        if [ -n "$(git log --merges ${{github.base_ref}}..${{github.head_ref}} --)" ]; then
          echo "Failure: Found merge commits. Please refer to https://github.com/motlin/forbid-merge-commits-action/blob/main/README.md for guidance."
          git log --merges ${{github.base_ref}}..${{github.head_ref}} --
          exit 1
        else
          echo "Success: No merge commits found"
        fi
      shell: bash
